using DataAccess.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BM2.DataAccess.Entities
{
    /*
        CREATE TABLE li (
            id         NUMBER NOT NULL,
            name       VARCHAR2(30) NOT NULL,
            descr      VARCHAR2(250),
            budown     VARCHAR2(30),
            critical   VARCHAR2(10),
            version    VARCHAR2(10),
            prodyr     VARCHAR2(10),
            usrcnt     NUMBER,
            cu_id      NUMBER NOT NULL,
            lity_id    NUMBER NOT NULL
        );
    */
    public class License : EntityBase {

        // id autogenerated
        [Required] public string Name { get; set; }
        public string Description { get; set; }
        public string BudgetOwner { get; set; }
        public string Critical { get; set; }
        public string Version { get; set; }
        public string ProductionYear { get; set; }
        public int Usercount { get; set; }

        public Customer Customer { get; set; }
        //public int CustomerId { get; set; }
        public LicenseType LicenseType { get; set; }
        //public int LicenseTypeId { get; set; }
    }

    /* methodes:
     *  Standard post(cu)
     *  Standard delete(id)
     *  Standard update(cu, id)
     *  Standard get() - allemaal
     *  Standard get(id) - specified
     *  **None standard get(cu_id) - geeft array  van alle records met gegeven cu_id
    */
}

