using DataAccess.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BM2.DataAccess.Entities
{
    /*
        CREATE TABLE li (
            id         NUMBER NOT NULL,
            name       VARCHAR2(30) NOT NULL,
            descr      VARCHAR2(250),
            budown     VARCHAR2(30),
            critical   VARCHAR2(10),
            version    VARCHAR2(10),
            prodyr     VARCHAR2(10),
            usrcnt     NUMBER,
            cu_id      NUMBER NOT NULL,
            lity_id    NUMBER NOT NULL
        );
    */
    public class License : EntityBase {

        // id autogenerated
        [Required] public string name { get; set; }
        public string descr { get; set; }
        public string budown { get; set; }
        public string critical { get; set; }
        public string version { get; set; }
        public string prodyr { get; set; }
        public decimal usrcnt { get; set; }

        public Cu cu { get; set; }
        public LicenseType lity { get; set; }
    }

    /* methodes:
     *  Standard post(cu)
     *  Standard delete(id)
     *  Standard update(cu, id)
     *  Standard get() - allemaal
     *  Standard get(id) - specified
     *  **None standard get(cu_id) - geeft array  van alle records met gegeven cu_id
    */
}

