using DataAccess.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BM2.DataAccess.Entities
{
    /*
        CREATE TABLE lico (
            id        NUMBER NOT NULL,
            licco     NUMBER,
            maintco   NUMBER,
            yr        NUMBER,
            li_id     NUMBER NOT NULL,
            coty_id   NUMBER NOT NULL
        );
    */
    public class Lico : EntityBase {

        // id autogenerated
        public decimal licco { get; set; }
        public decimal maintco { get; set; }
        public decimal yr { get; set; }

        public Li li { get; set; }
        public Coty coty { get; set; }

    }

    /* methodes:
    *  Standard post(cu)
    *  Standard delete(id)
    *  Standard update(cu, id)
    *  Standard get() - allemaal
    *  Standard get(id) - specified
    *  **None standard get(li_id) - geeft array  van alle records met gegeven li_id
    */
}

